### ISSUE TITLE
[windows][gcp] agent failed to get blobs to start job

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-agent#132]
Compilation of blobs worked on windows/gcp; but fetching the blobs to start a job failed. Agent logs:

https://gist.github.com/drnic/3cec1b90f3b4f36adbf51e5523eddaa5

**Comment by charlievieth** [comment]
We discovered this yesterday and are working on it ([story](https://www.pivotaltracker.com/story/show/147612317)).  This is due to the GCP Windows stemcell restarting shortly after boot.  After the restart the agent does not know about any previous tasks.

`[main] 2017/06/21 09:47:25 ERROR - Agent exited with error: received signal (interrupt): stopping now`

**Comment by charlievieth** [comment]
This issue is fixed in the `1093.X` stemcells, which are not yet available (aiming to cut a release this week), a GCP RC can be found here: [1093.0.0-build.1](https://s3.amazonaws.com/bosh-windows-stemcells-release-candidates/light-bosh-stemcell-1093.0.0-build.1-google-kvm-windows2016-go_agent.tgz).

**Comment by charlievieth** [comment]
This issue is fixed in the `1093.X` stemcells, which are not yet available (aiming to cut a release this week), a GCP RC can be found here: [1093.0.0-build.1](https://s3.amazonaws.com/bosh-windows-stemcells-release-candidates/light-bosh-stemcell-1093.0.0-build.1-google-kvm-windows2016-go_agent.tgz).
