### ISSUE TITLE
bosh-agent chown /var/vcap/data/{job} to root:vcap when it starts

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/bosh-agent#160]
What we observed
------------------

When the `bosh-agent` dies and is resurrected, it chowns `/var/vcap/data/garden` (and in fact all dirs in `/var/vcap/data` that have names that are also bosh job names) to `root:vcap`. Garden handles the ownership of this folder and doesn't expect other processes to interfere.

To reproduce
-------------

1. chown `/var/vcap/data/{some_job}` to something other than `root:vcap`
1. `pkill bosh-agent`
1. observe `bosh-agent` has been ressurected
1. observe that `/var/vcap/data/{some_job}` has ownership `root:vcap`

Stemcell version
----------------

bosh-warden-boshlite-ubuntu-trusty-go_agent/3541.2 (also observed in a non-lite environment that we don't own, sorry don't have the stemcell version)

From bosh docs
----------------

> Directory that is used by the release jobs to keep ephemeral data. Each *release job usually creates a sub-folder* with its name for namespacing (e.g. redis-server will place data into /var/vcap/data/redis-server).

This seems to indicate that bosh shouldn't be chowning things that are expected to be managed by bosh jobs.

Desired behaviour
------------------

bosh-agent doesn't chown subdirs of `/var/vcap/data`

Thanks,
- @hoegaarden
- @booleancat

**Comment by tjvman** [comment]
This is intended behavior (see [this story](https://www.pivotaltracker.com/story/show/143003487)). The `chown` will also happen on when the job is installed, not just on reboot - [here's the relevant call](https://github.com/cloudfoundry/bosh-agent/blob/master/agent/applier/jobs/rendered_job_applier.go#L87).

**Comment by ishustava** [comment]
Hey @tjvman @BooleanCat 

The Release Integration team also sees this issue. 

We have recently upgraded our bosh director, which had a CF deployed prior to that. During the upgrade, `bosh-agent` re-`chown`ed and re-`chmod`ed all the job directories in `/var/vcap/data`. This left diego-cells unavailable for `cf push`es. 

We think this may be a significant regression since it means that now by simply upgrading or recreating your bosh director, operators will experience `cf push` downtime.

This also affects, the `rep` component on the diego cell, which changes permissions of `/var/vcap/data/rep` to `vcap:vcap`.

cc @cppforlife @dsabeti

Thanks,
Iryna & Natalie, Release Integration Team

**Comment by cdutra** [comment]
@ishustava @BooleanCat This will be coming up on the next 3541 stemcell.

We have this [story](https://www.pivotaltracker.com/story/show/155716654) with the fix.

cc @mikexuu
