### ISSUE TITLE
How can we change the archive format and size of bosh-agent log?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-agent#194]
Sometimes, we need to check the bosh-agent log (`/var/vcap/bosh/current`) to know what problems happened there, but most of time,  the bosh agent log of that moment was already swept due to log rotation, the agent log is not archived in .tgz format, how can we configure the archive format and the size? Thanks.

/cc @edwardstudy

**Comment by voelzmo** [comment]
I remember having the conversation around keeping more agent logs with @cppforlife at some point. The gist was: We store the agent logs on the root partition (because other partitions/disks aren't available when the agent starts) and must therefore be very careful about how big those logs may get. At that point in time, it was considered to log *less* (e.g. when sending a heartbeat message you don't need to log it if there is nothing out of ordinary), or when the agent *doesn't* change files, because they are the same as already on disk. This would reduce the amount of logs and then 10MB of logs would last much longer.

Not sure what the current state of thinking is, though. @mfine30 @freddesbiens any opinions?

**Comment by mattcui** [comment]
Thanks, @voelzmo. Will the log move to the ephemeral disk after ephemeral disk is setup? And why aren't the rotated logs compressed to tgz? Do you mean we can configure to skip heartbeat messages? How? Thanks. We have much pain to find root cause in bosh agent log, the wanted messages were always swept.

/cc @dpb587 @jfmyers9

**Comment by h4xnoodle** [comment]
The agent uses svlogd defaults for its rotation. We have a [story](https://www.pivotaltracker.com/story/show/169690190) based on another set of use-cases that cause the logs to be aggressively rotated such that they are no longer useful at all. I agree it would be better to at least have better defaults/scale the defaults wrt disk size, and/or use the ephemeral space once initiated. We'll discuss these ideas in the aforementioned story.
