### ISSUE TITLE
What's the suggested version of golang to build bosh-agent?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/bosh-agent#227]
What's the suggested version of golang to build bosh-agent? What's the version is the community using? Thanks.

**Comment by h4xnoodle** [comment]
Our suggestion would be to use the latest version of golang to build, if you're building locally.

The bosh team bumps golang versions (whether that is because of a CVE, or new minor, etc) for building the agent in our CI before release. 

We're using a [docker image](https://github.com/cloudfoundry/bosh-agent/blob/master/ci/docker/Dockerfile#L26) that is bringing in the latest golang docker layer that was [updated about a month ago](https://hub.docker.com/r/bosh/agent) which contains:

```
$ docker run --it --rm bosh/agent
...
$ go version
go version go1.13.3 linux/amd64
``` 

This image was used to build the versions of the agent included in a stemcell since this image was updated. Hope that helps.

 Rebecca, BOSH
