### ISSUE TITLE
sfdisk -uM causes partitioning to fail on some linux platforms

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh-agent#265]
The agent currently performs disk partitioning using the `sfdisk -uM` command. The `-uM` option is unsupported on many linux platforms, and causes partitioning to fail on stemcells for such platforms.

Here is an example of such a failure.

```
2022-02-24_01:46:47.33033 [Cmd Runner] 2022/02/24 01:46:47 DEBUG - Running command 'sfdisk -uM /dev/sdc'
2022-02-24_01:46:47.33307 [Cmd Runner] 2022/02/24 01:46:47 DEBUG - Stdout: 
2022-02-24_01:46:47.33309 [Cmd Runner] 2022/02/24 01:46:47 DEBUG - Stderr: sfdisk: unsupported unit 'M'
2022-02-24_01:46:47.33310 [Cmd Runner] 2022/02/24 01:46:47 DEBUG - Successful: false (1)
2022-02-24_01:46:47.33310 [SfdiskPartitioner] 2022/02/24 01:46:47 ERROR - Failed with an error: Running command: 'sfdisk -uM /dev/sdc', stdout: '', stderr: 'sfdisk: unsupported unit 'M'
2022-02-24_01:46:47.33311 ': exit status 1
```

This [sfdisk man page](https://man7.org/linux/man-pages/man8/sfdisk.8.html#OPTIONS) doesn't list `-uM` as a supported unit, and says that the `-u` option is deprecated even for the single `-uS` unit that is documented.

The agent should be modified to replace the `sfdisk -uM` command with something that is more widely supported across linux platforms.

**Comment by rkoster** [comment]
@Justin-W Just out of interest which linux platform are you using? Asking because currently the only actively maintained stemcells are ubuntu based.

**Comment by Justin-W** [comment]
> @Justin-W Just out of interest which linux platform are you using? Asking because currently the only actively maintained stemcells are ubuntu based.

We are building custom RHEL 8.5 stemcells. We're almost finished (mostly just some STIG and CIS spec failures left to resolve).

We'd love to contribute that work back to this repo and to https://github.com/cloudfoundry/bosh-linux-stemcell-builder if that would be allowed. But we know that you guys intentionally removed support for Centos and RHEL from both of those repos previously (in d6be228a and https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/6acd0c9cf71edd6fab16b094e0d1083cbbd5ff5a, which have both been reverted and extended in our forks). We'd love to get our work on RHEL support merged back upstream if possible so that we don't have to maintain fully independent forks of both repos, but so far I've only been opening PRs for the bugs we're encountering that aren't directly coupled to RHEL/Centos.

Would you be open to accepting PRs which re-add RHEL/Centos support if we do the work?

**Comment by jpalermo** [comment]
Just to follow up on the question of PRs to bring RHEL back into the stemcell builder repo. I'd say it depends on the cost/value. This is just my opinion BTW, others may have different thoughts.

It was previously removed because it was unmaintained and just making things more complicated without adding value.

There was previously (many years ago) a push to get Centos/RHEL stemcells built so that CF could be run on top of them. But then it was discovered how much work would be required to make all the Bosh releases actually work on Centos/RHEL and the effort was abandoned. My guess is that most Bosh releases still live in that world, where even if there was a Centos/RHEL stemcell, they would fail to deploy on it. So adding complexity to the stemcell builder that can't really be utilized wouldn't make much sense.

However, if it doesn't add significant complexity, and it's being maintained and used by somebody, then it seems like it would make sense to bring it back.

**Comment by Justin-W** [comment]
> if it doesn't add significant complexity, and it's being maintained and used by somebody, then it seems like it would make sense to bring it back.

👍 

We are going to be actively running VMs on top of a RHEL 8.5 stemcell (8.5 to start; later releases to be added once they become available), regardless of whether it gets merged back into the main repo. And we will be having to maintain support for the RHEL functionality either way, to keep our environment up. But it would be a lot less of a merge maintenance and code divergence headache if we didn't have to do that work entirely within our fork and mostly-independently of the main repo, while simultaneously trying to maintain parity with upstream main/Ubuntu changes across repos.
