### ISSUE TITLE
WindowsNetManager.setupNetworking contains hard-coded sleep to 5s

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/bosh-agent#76]
That doesn't seem right, is this really necessary?
https://github.com/cloudfoundry/bosh-agent/blob/master/platform/net/windows_net_manager.go#L70

This also slows down the testsuite btw, as every test using `setupNetworking` now takes 5+ seconds:
```
• [SLOW TEST:5.004 seconds]
WindowsNetManager SetupNetworking Setting NIC settings sets the IP address and netmask on all interfaces, and the gateway on the default gateway interface
~/go/src/github.com/cloudfoundry/bosh-agent/platform/net/windows_net_manager_test.go:71
```

**Comment by tylerschultz** [comment]
cc @benmoss

**Comment by benmoss** [comment]
Hey @voelzmo, we have a [story](https://www.pivotaltracker.com/story/show/112358159) in our backlog to get rid of this very line. We introduced it as a bit of a hack because the Windows API we're using appears to be asynchronous without any obvious way to determine when the changes have taken effect. We agree it's not a great solution so we're going to have to find out a better way.

**Comment by cunnie** [comment]
Thanks @benmoss — Amin & I just ran into this problem, too.

**Comment by voelzmo** [comment]
@benmoss thanks for the hint. The comment in the story doesn't really sound like you would get to that soon, right? For me this is really an issue when you're touching the `net` package in the agent. The whole `WindowsNetManagerTest` takes more than 1 minute now, which makes running the package tests not really suiteable for quick turnarounds...

**Comment by benmoss** [comment]
It was looked at last week and we tried to figure out a way to poll something in Windows to see when the changes have taken effect, but couldn't. We reprioritized it because of this feedback. At worst we can isolate the tests with something like what Kubernetes does [here](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#kinds_of_tests) as a short-term solution for you.

**Comment by cppforlife** [comment]
@benmoss use Clock eg https://github.com/cloudfoundry/bosh-agent/blob/41c0683bb317adcf42178e70cde494bf18a0f648/app/app.go#L171

**Comment by xoebus** [comment]
I've changed it to inject a clock for now as part of https://github.com/cloudfoundry/bosh-agent/commit/fd376ea49f30bff9575399d55b57003a188dbb3a.
