### ISSUE TITLE
failed to run godep get to generate go dependency

### ISSUE THREAD

**Issue by zhang-hua** [cloudfoundry/bosh-agent#8]
When running ```godep get ./...```, it complains:
```
package github.com/cloudfoundry/bosh-micro-cli/deployer/registry

	imports github.com/cloudfoundry/bosh-micro-cli/deployer/registry

	imports github.com/cloudfoundry/bosh-micro-cli/deployer/registry: cannot find package "github.com/cloudfoundry/bosh-micro-cli/deployer/registry" in any of:

	/usr/local/go/src/pkg/github.com/cloudfoundry/bosh-micro-cli/deployer/registry (from $GOROOT)
	/Users/dongdong/Work/Projects/bosh-agent/src/github.com/cloudfoundry/bosh-micro-cli/deployer/registry (from $GOPATH)
godep: exit status 1 
```

Based on the investigation, we found the only dependency exists in integration test for fake-registry here:
https://github.com/cloudfoundry/bosh-agent/blob/587fefc980298ca993fd70e2024ca7d6b9e45629/integration/fake-registry/fake-registry.go#L7

The actual referenced code does exists here:
https://github.com/cloudfoundry/bosh-agent/tree/master/Godeps/_workspace/src/github.com/cloudfoundry/bosh-micro-cli/deployer/registry
but this is not synchronized with bosh-micro-cli repo which broke the godep.

-IBM pair Edward + Tom

**Comment by bosh-ci-push-pull** [comment]
The registry code was moved within the bosh-micro-cli. The bosh-agent
imports have not yet been updated to reflect that change. You won't be able
to bump those vendored dependencies until that's done.

If you do a godep restore instead, that will check out the vendored
revisions into your go workspace, rather than checking out the latests
revisions.

Or you can fix the import yourself and submit a PR (or do you guys have
commit access?).

-Karl Isenberg
Pivotal BOSH Team

**Comment by zhang-hua** [comment]
ok. we don't have commit access. we will submit a PR for you to review. Thanks!

-IBM pair Edward + Tom

**Comment by cppforlife** [comment]
Closing since PR was merged. Reopen if it's still a problem.
